spring:
  application:
    name: user-management-functionality-app

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/test_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: santoshlimbale76@gmail.com
    password: wsmpfquiygapujnj
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 9090
  
user-api:
 messages:
  RegistrationSaveSuccess: Registeration done Successfully
  RegistrationSaveFailed: Registeration Failed 
  UserDeleted: User deleted successfully
  UserDeleteFailed: User Id not Found
  StatusChangeSuccess: Status Change Successfully
  StatusChangFail: Status Change Fail
  AccountActive : Account Active   
  AccountInactive: Account In-Active
  LoginSuccess : Login Success
  LoginFailed : Invalid credetainls
  RegistrationFailed: Registration Failed
