
spring:
  application:
    name: user-management-functionality-app
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/test_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: santoshlimbale77@rediffmail.com

    
server:
  port: 9090
  
    
